### ISSUE TITLE
using external nlohmann-json?

### ISSUE THREAD

**Issue by lgarren** [BNLNPPS/nopayloadclient#6]
Is there a plan to allow building nopayloadclient with an external nlohmann-json distribution?  This will help us greatly, since nlohmann-json is used in a number of different places and we'd like to avoid unintentional conflicts.

**Comment by ligerlac** [comment]
You can now specify to use an external nlohmann-json header like so:
`cmake -S . -B build -DINCLUDE_DIR_NLOHMANN_JSON=<nlohmann_include_dir>`
If omitted, the header that is shipped with nopayloadclient (under `contrib/`) will be used.

**Comment by lgarren** [comment]
Thank you!

Lynn

________________________________________

**Comment by lgarren** [comment]
@ligerlac Would you make a new tag that includes this functionality?  Thanks!

**Comment by ligerlac** [comment]
Done. It is now tagged as v0.0.2

**Comment by lgarren** [comment]
@ligerlac  It seems that json.hpp is still being installed from contrib.  When an external distribution of  nlohmann-json is used, we would prefer that the nopayloadclient include/nlohmann directory not be installed.  Is that a problem?

**Comment by ligerlac** [comment]
I had forgotten to delete the header under `include`. It should be fixed now. Let me know if it's okay like this and I will create a new tag.

**Comment by lgarren** [comment]
This works.  Waiting for the new tag.

**Comment by lgarren** [comment]
Happy with v0.0.3.  Closing this, but see new PR.
